version: '3.5'

services:
 mysql:
    image: mysql:5.7
    volumes:
       - ./db:/var/lib/mysql
       - ./mysql_src:/home/mysql_src/
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: toor
       MYSQL_DATABASE: test_db
    networks:
      - "web"
    ports:
      - 3306:3306

 php:
    build: ./php/
    restart: always
    networks:
      - "web"
    
 redis:
   image: sameersbn/redis:latest
   networks:
      - "web"
   ports:
      - 6379:6379


networks:
  web:
    external: true
